### ISSUE TITLE
다크모드에서 toast 색상 이슈

### ISSUE THREAD

**Issue by jeamxn** [jeamin-0927/dimigoin-pull-service#18]
다크모드에서 `toast` 색상이 이상하게 나옴 (해결해줘~~~)

![CleanShot 2024-03-21 at 10 14 18@2x](https://github.com/jeamxn/dimigoin-pull-service/assets/85402289/f5cbd5f9-99c8-4b94-9b42-d8ca4e80e5d4)

**Comment by jeamxn** [comment]
가끔 이러네 왜 이러지

**Comment by yeonfish6040** [comment]
새로고침하면 해결되네요...?

**Comment by jeamxn** [comment]
해결함(어제)
